codecov:
  notify:
    require_ci_to_pass: false	# always post
    after_n_builds: 2		# user and kernel

coverage:
  precision: 1			# 0 decimals of precision
  round: nearest        # Round to nearest precision point
  range: "50...90"		# red -> yellow -> green

  status:
    project:
      default:
        threshold: 1%		# allow 1% coverage variance

    patch:
      default:
        threshold: 1%		# allow 1% coverage variance

comment:
layout: diff, files 

ignore:
  -Adapter.java
  -*/ChatActivity.java
  -*/app/src/main/java
  
